### ISSUE TITLE
feat: unify the package managers used in examples

### ISSUE THREAD

**Issue by MathurAditya724** [honojs/examples#220]
We need to unify the package managers used in this project, but it is not related to this PR. I think `npm` is a good choice because it's general.

_Originally posted by @yusukebe in https://github.com/honojs/examples/pull/219#discussion_r1858601057_

**Comment by MathurAditya724** [comment]
I agree that unifying the package manager is important, but since the repo currently uses `yarn` workspaces, switching to `npm` might not be straightforward. If we want consistency, we could either stick with `yarn` across all examples or consider moving to `pnpm`, which offers better workspace support and aligns closely with `npm`.  

Regardless of the decision, we should also update the main `README.md` to reflect the unified commands and ensure they are clear and consistent.

**Comment by yusukebe** [comment]
@MathurAditya724 

Thank you for creating the issue.

In my opinion, `npm` is good to unify the entire project, including the workspace. I am rethinking `npm` is a good choice for the package manager because it is the default of Node.js, and its functions are enough for projects that are not so big.

**Comment by MathurAditya724** [comment]
Sounds good, I will start working on a PR
