### ISSUE TITLE
feat: monorepo Hono RPC example

### ISSUE THREAD

**Issue by sor4chi** [honojs/examples#94]
Are there any example of modern-monorepo-stack (pnpm and turborepo) using Hono RPC?
If not, I want to add!

Did this still the type of client is unkonw. Ran pnpm install and restrated the server.

**Comment by yusukebe** [comment]
Hi @sor4chi !

Thank you for your proposal.

> Are there any example of modern-monorepo-stack (pnpm and turborepo) using Hono RPC?

May be not. But I think it's not necessary to place it here(this repo) because using "pnpm" or "turborepo" isn't essential to the core functionalities of Hono, as they are more about tooling.

The good solution is that you make it on GitHub public repo and link to this from such as awesome Hono.

cc: @yudai-nkt

**Comment by sor4chi** [comment]
Hi @yusukebe

Wow, I didn’t know there was such a community. I‘d like to submit a scaffold that uses Hono RPC in a microservice and multi-package that uses service binding. Thank you for the suggestion!

**Comment by yudai-nkt** [comment]
Hi, thanks for cc! Submission to Awesome Hono is always welcome, so please follow the instruction at https://awesome-hono.y-nkt.workers.dev/submission if you are interested.

I haven't spent much time on it lately, but will finish the missing part in the coming weeks. In particular, I'm wondering where to deploy; Pages are generally preferred over Workers Sites to serve static files, but Sites in this project is more of a data persistence everyone can easily contribute to than just a static file serving.
